### ISSUE TITLE
command 'extension.previewPlantUML' not found

### ISSUE THREAD

**Issue by JuloMi** [runceel/plantumlpreview#10]
when choosing choosing 'PlantUML Preview' from Command Palette

Extension can be seen among installed. Uninstall option for it is available.
VS Code 1.6.1
PlantUML 8048
okazuki PlantUML plugin 0.1.5

**Comment by runceel** [comment]
Did you set environment value?
- PLANTUML_HOME
- JAVA_HOME

Please show readme.md.

**Comment by JuloMi** [comment]
Yes, I think, I did.
D:_work_\plantUML>set | grep PLANT
PLANTUML_HOME=D:_work_\plantUML

D:_work_\plantUML>set | grep JAVA
JAVA_HOME="c:\Program Files\Java\jre8u101\bin\"

**Comment by runceel** [comment]
OK.

JAVA_HOME is Java installed folder.
It is "c:\Program Files\Java\jre8u101".

Could you try.

**Comment by JuloMi** [comment]
D:_work_\plantUML>"c:\Program Files\Java\jre8u101\bin\java"
Usage: java [-options] class [args...](to execute a class)
   or  java [-options] -jar jarfile [args...](to execute a jar file)
...

Seems to be OK.

**Comment by JuloMi** [comment]
my fault. I ran it from a different window. Now the error is "Unable to open 'PlantUML Preview;: write EPIPE

**Comment by runceel** [comment]
Could you run this command?

```
"%JAVA_HOME%\bin\java" -jar "%PLANTUML_HOME%\plantuml.jar"
```

This VSCode extension just execute this command.

**Comment by JuloMi** [comment]
I have changed JAVA_HOME 
from
JAVA_HOME="c:\Program Files\Java\jre8u101\bin\"
to 
JAVA_HOME="c:\Program Files\Java\jre8u101

and then ran
D:_work_\plantUML>"%JAVA_HOME%\bin\java" -jar "%PLANTUML_HOME%\plantuml.jar"
'""c:\Program' is not recognized as an internal or external command,
operable program or batch file.

"c:\Program Files\Java\jre8u101\bin\java" -jar "%PLANTUML_HOME%\plantuml.jar"
-runs GUI of PlantUML

**Comment by runceel** [comment]
Are your JAVA_HOME "c:\Program Files\Java\jre8u101??
I think that you should remove double quote.

**Comment by JuloMi** [comment]
Thank you very much for your help. It works now.

D:_work_\plantUML>set JAVA_HOME=c:\Program Files\Java\jre8u101
D:_work_\plantUML>set | grep JAVA
JAVA_HOME=c:\Program Files\Java\jre8u101
D:_work_\plantUML>"%JAVA_HOME%\bin\java" -jar "%PLANTUML_HOME%\plantuml.jar"
-runs app
Double quotes were intended to avoid problems with the space in the path. Without them it works.

**Comment by runceel** [comment]
I'm glad to become your help.

Tyank you.
