### ISSUE TITLE
Config PLANTUML_JAR rather than PLANTUML_HOME

### ISSUE THREAD

**Issue by leira** [runceel/plantumlpreview#11]
plantuml installed with homebrew on Mac has version number in the jar file name, like this:

/usr/local/Cellar/plantuml/8046/plantuml.8046.jar

I can of course link it into a plantuml.jar some where, then specify that location as PLANTUML_HOME, but that needs extra work, and I have to do it every time new version of plantuml comes out.

If it's just the jar file is needed by plantumlpreview, then why not specify the jar file path in a PLANTUML_JAR setting, rather than PLANTUML_HOME and have to construct the jar file path?

**Comment by runceel** [comment]
Thank you for your feedback.

But I busy now. Please wait after next week.

**Comment by runceel** [comment]
I had free time.
I fixed this issue!!

I released v0.1.6. Could you try it?

**Comment by leira** [comment]
You are awesome! I will try it right after get home.

**Comment by leira** [comment]
I just tried with new PLANTUML_JAR, and it worked perfectly~ Thanks a lot!

**Comment by runceel** [comment]
You are welcome!
