### ISSUE TITLE
command 'extension.previewplantuml' not found

### ISSUE THREAD

**Issue by llagit** [runceel/plantumlpreview#13]
I have installed the extension on my VScode.
I got "command 'extension.previewplantuml' not found" when I run "PlantUML preview".

- Extension Installed
- JAVA_HOME created
- PLANTUML_JAR created
- GRAPHVIZ_DOT created

**Comment by runceel** [comment]
Thank you.

I want to see your env value setting dialog screen shot.

**Comment by llagit** [comment]
Oooops... I'm sorry. I don't know why my env variables has not been written (my fault... probably an error on my batch).

All soved. Thank you.
