### ISSUE TITLE
Unable to open 'PlantUML Preview': write EPIPE.

### ISSUE THREAD

**Issue by tomigaprv** [runceel/plantumlpreview#15]
During running preview I got following error:

Unable to open 'PlantUML Preview': write EPIPE.

Nothing is generated.

Any hint?

**Comment by runceel** [comment]
I want to see your environment value setting.
for example, screen shot.

**Comment by tomigaprv** [comment]
Could you be more specific. Which files (or from which view) you want to have screenshot.

**Comment by runceel** [comment]
If your OS is Windows then Environment value setting window screen shot.
I want to know your real setting value.

Maybe,  If your setting value is `"C:\Program Files\Java\j2sdk1.8.*"` that include double quote then you should remove double quote.
Otherwise, If JAVA_HOME environment value is `C:\Program Files\Java\j2sdk1.8.*\bin` then you remove bin.

**Comment by tomigaprv** [comment]
Ok, it is on my work computer I will provide your info more info on Monday. Thanks.

**Comment by tomigaprv** [comment]
Some of my settings:
GRAPHVIZ_DOT=c:\Program Files (x86)\Graphviz2.38\bin\dot.exe
HOMEDRIVE=H:
HOMEPATH=\
JAVA_HOME="C:\Program Files (x86)\Java\jre1.8.0_111"
LogPath=C:\WINDOWS\Logs\Siemens
Path=C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\RSA SecurID Token Common;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\Syst
em32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\WebEx\Productivity Tools;C:\Program Files (x86)\Sennheiser\SoftphoneSDK\;C:\Program Files (x86)\SafeCom\Safe
ComPrintClient;C:\Python27;C:\Python27\Scripts;C:\Program Files\TortoiseSVN\bin;;C:\Program Files (x86)\Microsoft VS Code\bin;C:\Python27;C:\Python27\Scripts
PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
PLANTUML_HOME=C:\bin
PLANTUML_JAR=c:\bin\plantuml.jar

**Comment by runceel** [comment]
Thank you.

You should remove to double quote in JAVA_HOME.

**Comment by tomigaprv** [comment]
Thanks you are right. Now it works :)

**Comment by ca0v** [comment]
I am getting the same error:

JAVA_HOME=C:\Program Files\Java\jdk1.8.0_171

```
Error: write EPIPE
at afterWriteDispatched (internal/stream_base_commons.js:149:25)
at writeGeneric (internal/stream_base_commons.js:140:3)
at Socket._writeGeneric (net.js:776:11)
at Socket._write (net.js:788:8)
at doWrite (_stream_writable.js:435:12)
at writeOrBuffer (_stream_writable.js:419:5)
at Socket.Writable.write (_stream_writable.js:309:11)
at c:\Users\calix\.vscode\extensions\jebbs.plantuml-2.13.14\out\src\plantuml\renders\local.js:112:35
at runMicrotasks ()
at processTicksAndRejections (internal/process/task_queues.js:94:5)
```
