### ISSUE TITLE
Typo error PNALTUML_JAR

### ISSUE THREAD

**Issue by tomigaprv** [runceel/plantumlpreview#16]
I have found typo error 

PNALTUML_JAR -> PLANTUML_JAR

In following code

`if (!process.env['PLANTUML_HOME'] || !process.env['PNALTUML_JAR']) { vscode.window.showErrorMessage('Set enviroment variable. PLANTUML_HOME or PLANTUML_JAR.'); }`

**Comment by runceel** [comment]
Thank you for your suggestion.

I fixed typo.
