### ISSUE TITLE
[New Feature] Support for reStructuredText file types

### ISSUE THREAD

**Issue by tomigaprv** [runceel/plantumlpreview#17]
Apart from plain text it would be nice to have support for reSturcturedText which is used for writing documentation in Sphinx.

I want to use your plugin together with following extension available under following link
https://marketplace.visualstudio.com/items?itemName=lextudio.restructuredtext

and here GitHub project
https://github.com/vscode-restructuredtext/vscode-restructuredtext

**Comment by runceel** [comment]
Thank you for your feedback.

But, I think that PlantUML don't support reStructuredText.

**Comment by tomigaprv** [comment]
My idea was to use your plugin together with reStructuredText plugin so I just wanted that you add in your plugin support for additional file type apart from "plain text".
Somewhere in `createPlantumlSnippet` function just extend the condition

`if (!(editor.document.languageId === 'plaintext')) {
                return this.errorSnippet("not plaintext");
            }` 

In reStructuredText mode currently I will have just "not plaintext" message. After change I was expecting that I will able to see just pure text + generated UML diagrams... (it is enough for me)

Does my  assumption is correct?

Concerning not supporting "uml" by reStructuredText I am using Sphinx environment which can handle both restructuredText with "embeded" uml diagrams.

**Comment by runceel** [comment]
I added `restructuredtext` support.
Please try use with reSturcturedText.

**Comment by tomigaprv** [comment]
Greate! Thanks a lot. I will try on Monday and provide feedback to you.

**Comment by tomigaprv** [comment]
ok, restructuredText files are not blocked now but I still cannot get previou because of "Unable to open 'PlantUML Preview': write EPIPE" :(. At least thanks for this change.
