### ISSUE TITLE
command 'extension.previewPlantUML' not found

### ISSUE THREAD

**Issue by jaemyoun** [runceel/plantumlpreview#18]
The command 'PlantUML Preview' did not work. Other commands also are same.

The vscode is running on Ubuntu 14.04.
The environment is follow:
`JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64/jre`
`PLANTUML_JAR=/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/plantuml.jar`
`GRAPHVIZ_DOT=/usr/bin/dot`

Any one help me?

**Comment by runceel** [comment]
Can you execute plantuml.jar at command line?

**Comment by jaemyoun** [comment]
@runceel The command line only works with absolute path of plantuml.jar.

`$ java -jar plantuml.jar -verbose a`
`Error: Unable to access jarfile plantuml.jar`
`$ java -jar $JAVA_HOME/lib/plantuml.jar -verbose a`
`(0.000 - 240 Mo) 234 Mo - PlantUML Version 8050`
`...`

**Comment by runceel** [comment]
OK.

Could you try this.

```
$JAVA_HOME/bin/java $PLANTUML_JAR -verbose a
```

okazuki PlantUML execute this command.

**Comment by jaemyoun** [comment]
@runceel The `-jar` option is needed. 

`$ $JAVA_HOME/bin/java $PLANTUML_JAR -verbose a`
`Error: Could not find or load main class .usr.lib.jvm.java-8-openjdk-amd64.jre.lib.plantuml.jar`
`$ $JAVA_HOME/bin/java -jar $PLANTUML_JAR -verbose a`
`(0.000 - 240 Mo) 234 Mo - PlantUML Version 8050`
`...`

**Comment by runceel** [comment]
hmm....

Could you set OKAZUKIUML_DEBUG=1 env value.
Then also, Execute PlantUML Preview command.

Please tell me error message detail.

**Comment by derchirurg** [comment]
@runceel  Where is the log stored?

**Comment by runceel** [comment]
Error message appear to VSCode message area.

**Comment by AbangSD** [comment]
I have this problem, too.

``` shell
$JAVA_HOME/bin/java -jar $PLANTUML_JAR -verbose a
(0.000 - 64 Mo) 57 Mo - PlantUML Version 1.2018.01
(0.032 - 64 Mo) 56 Mo - GraphicsEnvironment.isHeadless() false
```

**Comment by AbangSD** [comment]
What should I do? Can you help me?

**Comment by AbangSD** [comment]
I am so sorry, I missed "export" in profile.
Thank you a lot.
