### ISSUE TITLE
Preview does not render correctly

### ISSUE THREAD

**Issue by derchirurg** [runceel/plantumlpreview#19]
The preview window does not show the UML correctly. Please see the attached image.
The export does it correctly with background color.
![plantuml](https://cloud.githubusercontent.com/assets/22213966/21419556/ab36293a-c828-11e6-8b38-d5c45bc25a49.png)

Correct:
![plantuml](https://cloud.githubusercontent.com/assets/22213966/21419568/bb930e60-c828-11e6-893b-8044924840f8.png)

**Comment by derchirurg** [comment]
I found a solution. I just need to add on top
`skinparam style strictuml`

So it looks like:
```
@startuml
skinparam style strictuml
class Test {
    +string ToString()
}
@enduml
```

**Comment by runceel** [comment]
Thank you for you feedback!
