### ISSUE TITLE
command 'extension.previewPlantUML' not found

### ISSUE THREAD

**Issue by Heboy** [runceel/plantumlpreview#21]
Could you help me to check my ~/.bash_profile file?

export JAVA_HOME="/Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home"
export PLANTUML_JAR="/usr/local/Cellar/plantuml/8048/libexec/plantuml.jar"

**Comment by runceel** [comment]
@Heboy Could you remove double quote from path?

**Comment by Heboy** [comment]
I restart my mac and it going well, thank you

my ~/.bash.profile is below, it`s correct for me and hope to help others

```
export JAVA_HOME="/Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home"

export PLANTUML_JAR="/usr/local/Cellar/plantuml/8048/libexec/plantuml.jar"

export GRAPHVIZ_DOT="/usr/local/bin/dot"

source ~/.bashrc
```

**Comment by runceel** [comment]
Thank you!
