### ISSUE TITLE
Preview only shows empty square

### ISSUE THREAD

**Issue by valera-g** [runceel/plantumlpreview#22]
Hi,

I've setup all env variables and ensured PlantUML runs from command line correctly. Unfortunately preview only shows empty rectangle instead of expected rendered diagram.

Example code:
```
@startuml
skinparam style strictuml
class Object {
}
@enduml
```

Command used in cmd:
`java -jar "%PLANTUML_JAR%\plantuml.jar" plugin-lifecycle.plantuml `

Result PNG:
![plugin-lifecycle](https://cloud.githubusercontent.com/assets/7810062/23736741/0eab3c16-045c-11e7-831d-25c9ff4bf461.png)

Screenshot of the VSC:
![capture](https://cloud.githubusercontent.com/assets/7810062/23736706/d191a6b2-045b-11e7-92da-dc74a0951234.PNG)

Any idea what can be wrong?

Thank you,
Valera.

**Comment by runceel** [comment]
Thank you for your feedback.
I installed PlantUML and Graphiz.
And install okazuki PlantUML to VSCode.
Sett env variable PLANTUML_JAR and JAVA_HOME.
I can write plantuml file then displayed diagram.

<img width="463" alt="default" src="https://cloud.githubusercontent.com/assets/79868/23829828/1af0fe8a-073f-11e7-8c41-6d66b734fa3f.PNG">

**Comment by VaclavSynacek** [comment]
@valera-g  Set the PLANTUML_JAR to the jar, not to the directory containing the jar. I had the same mistake and got the same bad output as your screenshot. After correcting PLANTUML_JAR env variable all works fine.

@runceel Issue should be closed.

**Comment by valera-g** [comment]
> @valera-g Set the PLANTUML_JAR to the jar, not to the directory containing the jar. I had the same mistake and got the same bad output as your screenshot. After correcting PLANTUML_JAR env variable all works fine.
> 
> @runceel Issue should be closed.

This really worked. Thanks! My bad.
