### ISSUE TITLE
Doesn't work on Windows 10

### ISSUE THREAD

**Issue by mastoj** [runceel/plantumlpreview#3]
I can't get the plugin to run on my windows 10 machine. I have set the PLANTUML_HOME, JAVA_HOME and TEMP env. variables, but I still get a message that I haven't done so. Also, it complains that the command 'extension.exportPlantUML' is not found, but I guess that is a error caused by the first problem.

Anything I can do to get debugging info?

**Comment by runceel** [comment]
I tested Windows 10 AU machines and Windows 7 machine.
Did you rebooted VS Code after have set env?

Tyank you.

**Comment by mastoj** [comment]
Yes. Tried restart code without success. Does it matter which profile you
set the variables on? I mean, machine or personal profile.

Want be able to try it again until next week, but if you know something I
could try I do it then.

An alternative solution for you might be that one can override those
settings in the configuration of the extension.

**Comment by runceel** [comment]
This check logic is very simple.

``` javascript
    if (!process.env['PLANTUML_HOME'] || !process.env['JAVA_HOME'] || !process.env['TEMP']) {
        vscode.window.showErrorMessage('Setup enviroment variable. PLANTUML_HOME, JAVA_HOME, TEMP'); 
        return;
    }
```

I set personal pfofile.(sorry it is japanese language.) 

<img width="423" alt="default" src="https://cloud.githubusercontent.com/assets/79868/18208166/4889a6d8-7169-11e6-8f4c-c4a87a3b762c.PNG">

Can you execute plantuml that command?

```
"%JAVA_HOME%\bin\java.exe" -jar "%PLANTUML_HOME%\plantuml.jar"
```

**Comment by mastoj** [comment]
I can't try until next week.

Maybe you can add a message that tells the user which variable that is
missing?

**Comment by runceel** [comment]
I released v0.0.6. 
Error message improvement.

Separate error message to env value.

``` javascript
if (!process.env['PLANTUML_HOME'] || !process.env['JAVA_HOME'] || !process.env['TEMP']) {
    if (!process.env['PLANTUML_HOME']) { vscode.window.showErrorMessage('Set enviroment variable. PLANTUML_HOME.'); } 
    if (!process.env['JAVA_HOME']) { vscode.window.showErrorMessage('Set enviroment variable. JAVA_HOME.'); } 
    if (!process.env['TEMP']) { vscode.window.showErrorMessage('Set enviroment variable. TEMP.'); } 
    return;
}
```

**Comment by runceel** [comment]
What is a status?

**Comment by mastoj** [comment]
I tried it now and it works fine after update! Really nice!

**Comment by runceel** [comment]
Thenk you!!
