### ISSUE TITLE
macでの動作

### ISSUE THREAD

**Issue by baron-tommy** [runceel/plantumlpreview#4]
PlantUML Preview 実行後
command 'extension.previewPlantUML' not found
と表示されます

versiohは0.0.8

``` bash
tommyMac:~ Tommy$ echo $JAVA_HOME
/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home
tommyMac:~ Tommy$ echo $PLANTUML_HOME
/Users/Tommy/Dropbox/developer/jar
tommyMac:~ Tommy$ echo $TMP
/tmp
tommyMac:~ Tommy$
```

**Comment by runceel** [comment]
`TMP`ではなく`TEMP`環境変数は定義されてますか？

そのエラーが出るときは、一緒に何か環境変数の定義がないっていうエラーも出てそうな気がするのですがどうでしょうか。

**Comment by baron-tommy** [comment]
TMP -> TEMP
見間違えていました
すみません

ありがとうございます。

**Comment by runceel** [comment]
解決して良かったですー。

**Comment by baron-tommy** [comment]
いつも
`$TMP`でしていましたので、、、
恥を晒してしまいました

macでの利用ですので、winと違う視点の発見があるかもしれません
なにかありましたらissuesにて報告いたします
