### ISSUE TITLE
preview shows "broken link"

### ISSUE THREAD

**Issue by mihael74** [runceel/plantumlpreview#5]
hello

Unfortunately, preview shows a brocken link only.
![capture](https://cloud.githubusercontent.com/assets/22000262/18242413/7ef692c8-7356-11e6-89b7-df2bd96eaf73.PNG)

The export works :)

cheers,
Mihael

**Comment by runceel** [comment]
Thank you for your feedback.

Sorry. v0.0.10 and v0.0.11 is broken. 
Please use v0.0.12.

**Comment by mihael74** [comment]
It now works:)
Thank you!

**Comment by runceel** [comment]
Your wellcome!

Thank you.
