### ISSUE TITLE
Unable to open 'PlantUML Preview': write EPIPE.

### ISSUE THREAD

**Issue by edwin-alvarez** [runceel/plantumlpreview#8]
this error happends when I try to do 'preview'

**Comment by runceel** [comment]
did you setup env value?

**Comment by edwin-alvarez** [comment]
yes I did, I configured it as User variable and system variable and didnt work. I have 
GRAPHVIZ_DOT = C:\TEMP\UML\graphviz-2.38\bin\dot.exe
JAVA_HOME = C:\Program Files\Java\jdk1.8.0_101\bin
PLANTUML_HOME = C:\TEMP\UML\plantuml.jar

![puml](https://cloud.githubusercontent.com/assets/5774873/18803685/27a11a84-81a7-11e6-992c-b10d0a2d3fbf.PNG)

NOTE: if I run plantuml.jar outside VSCode (manually) it works fine

**Comment by runceel** [comment]
OK.

PLANTUML_HOME is directory of plantuml.jar. True value is `C:\TEMP\UML`. And JAVA_HOME value is JDK installed directory. It is `C:\Program Files\Java\jdk1.8.0_101`.
Please try.

**Comment by edwin-alvarez** [comment]
works great :)

**Comment by runceel** [comment]
You are wellcome.
