### ISSUE TITLE
Unable to generate preview

### ISSUE THREAD

**Issue by muffadalis** [runceel/plantumlpreview#9]
The export is not working for me after the update. Is anyone else facing the issue? I am running VSCode version 1.5.3 on Windows 10.

**Comment by runceel** [comment]
I can export png on VSCode 1.5.3 on Windows 10 now.

Export command changed behavior at v0.1.15. 
- execute export png
- set output directory(new!)
- done export

**Comment by muffadalis** [comment]
I have tried that but not luck. If I give a folder that doest not exists then its creates the folder but no png file there. I tried installing GraphViz but still no image. Are there logs I can look at?

**Comment by runceel** [comment]
Can you export to png when plantuml command executed directly?

And you can see plantuml std error output in VSCode.
- Set env value `OKAZUKIUML_DEBUG` = 1.
- export png
- if plantuml output std error then show error message.

**Comment by muffadalis** [comment]
My bad. I did not have @startuml & @enduml in the text. Thanks for all you help.

**Comment by runceel** [comment]
i'm glad.
